// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgx8SWi2VtLlnp6gi9HEqgO_rdhHiN25k',
    appId: '1:1030722043041:web:aeab57862279107cb8c4e0',
    messagingSenderId: '1030722043041',
    projectId: 'xchat-16d1d',
    authDomain: 'xchat-16d1d.firebaseapp.com',
    storageBucket: 'xchat-16d1d.firebasestorage.app',
    measurementId: 'G-E7PZB970VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jXmdoM9-FYsNUYVR-6cq5DygKlK0QhY',
    appId: '1:1030722043041:android:4ec4879c625ef4dfb8c4e0',
    messagingSenderId: '1030722043041',
    projectId: 'xchat-16d1d',
    storageBucket: 'xchat-16d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpv1CcKkIVjq76x5YMGSHB87i0oajYt8',
    appId: '1:1030722043041:ios:36fba050192fc1fdb8c4e0',
    messagingSenderId: '1030722043041',
    projectId: 'xchat-16d1d',
    storageBucket: 'xchat-16d1d.firebasestorage.app',
    androidClientId: '1030722043041-d75vjv0fsqijo2snpqd695a3r7npfsgh.apps.googleusercontent.com',
    iosClientId: '1030722043041-5i1uplqjineliq2l287lm0a9gv2uem9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.xChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpv1CcKkIVjq76x5YMGSHB87i0oajYt8',
    appId: '1:1030722043041:ios:36fba050192fc1fdb8c4e0',
    messagingSenderId: '1030722043041',
    projectId: 'xchat-16d1d',
    storageBucket: 'xchat-16d1d.firebasestorage.app',
    androidClientId: '1030722043041-d75vjv0fsqijo2snpqd695a3r7npfsgh.apps.googleusercontent.com',
    iosClientId: '1030722043041-5i1uplqjineliq2l287lm0a9gv2uem9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.xChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgx8SWi2VtLlnp6gi9HEqgO_rdhHiN25k',
    appId: '1:1030722043041:web:0938d20b8778dafdb8c4e0',
    messagingSenderId: '1030722043041',
    projectId: 'xchat-16d1d',
    authDomain: 'xchat-16d1d.firebaseapp.com',
    storageBucket: 'xchat-16d1d.firebasestorage.app',
    measurementId: 'G-E24KZSGNBR',
  );
}
